const ENVIRONMENT = Object.freeze({
  ENVIRONMENT_NODE_ENV: process.env.ENVIRONMENT_NODE_ENV,
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
  ENVIRONMENT_S3_BUKET_NAME: process.env.ENVIRONMENT_S3_BUKET_NAME,
});
module.exports = ENVIRONMENT;
